---
title: 'Part 2: Classification on Wine Review Data Set'
author: "Rafael Melendez"
subheading: 3/25/2023
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  chunk_output_type: inline
---
```{r}
wdata <- read.csv("C:\\Users\\bayon\\OneDrive\\Documents\\winemag-data_first150k.csv", header = TRUE, sep = ",")
wdata

w_rem <- wdata[1:15000, ]
w_rem <- w_rem[!is.na(w_rem$price),]
w_rem <- w_rem[, -1]
w_rem <- w_rem[!is.na(w_rem$region_1),]
w_rem <- w_rem[!is.na(w_rem$region_2),]

```
```{r}
#A
str(wdata)

set.seed(1234)
i <- sample(1:nrow(wdata), nrow(wdata)*0.8, replace=FALSE)
train <- wdata[i,]
test <- wdata[-i,]
cl <- wdata[i,]

names(wdata)
ncol(wdata)
tail(wdata, n = 10)
colSums(is.na(wdata))
summary(wine_train)
summary(wine_test)
```
```{r}
#B
plot(wdata$price~wdata$points, xlab = "Points", ylab = "Price")
abline(lm(wdata$price~wdata$points), col="green4")

plot(wdata$points, wdata$price, pch=21, bg=c("green4","blue4", "orange2", "red3", "yellow2", "purple4")
     [unclass(wdata$country)], main="Wine Review Data")
```

```{r}
#C: Logistic Model
glm1 <- glm(as.factor(wdata$price)~wdata$points, data = train, family = "binomial")
summary(glm1)

pred <- predict(glm1, newdata = test)
pred <- exp(pred1)
cor <- cor(pred, test$points)
mse <- mean((pred-test$points)^2)
rmse <- sqrt(mse)
```

```{r}
#C: kNN Classification

set.seed(1234)
i <- sample(2, nrow(wdata), replace=TRUE, prob=c(0.8, 0.2))
wtrain <- wdata[i==1, 1:4]
wtest <- wdata[i==2, 1:4]
wTrainL <- wdata[i==1, 5]
wTestL <- wdata[i==2, 5]

library(class)
wine_pred <- knn(train=iris.train, test=iris.test, cl=iris.trainLabels, k=3)

results <- wine_pred == wTestL
acc <- length(which(results==TRUE)) / length(results)
table(results, wine_pred)
acc

```

```{r}
#C: Decision Trees
library(rpart)
#install.packages("tree")
library(tree)
wine_tree <- rpart(variety~., data = wdata, method = "class")
summary(wine_tree)
plot(wine_tree, uniform=TRUE)
text(wine_tree, use.n=TRUE, all=TRUE, cex=.6)


set.seed(1958)
i <- sample(1:nrow(wdata), nrow(wdata)*0.8, replace=FALSE)
train <- wdata[i,]
test <- wdata[-i,]
wtree <- tree(variety~., data=train)
wpred <- predict(wtree, newdata=test, type="class")
table(pred, test$variety)
mean(pred==test$variety)

```
